[package]
name = "zrest"
version = "0.1.0"
authors = ["Valery Vybornov <vvybornov@gmail.com>"]

[dependencies]
log = "0.3"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
hyper-tls = "0.1"
native-tls = "0.1"
mime = "0.2"