[package]
name = "zgwlib"
version = "0.1.0"
authors = ["Valery Vybornov <vvybornov@gmail.com>"]

[dependencies]
log = "0.3"
simplelog = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"

[target.'cfg(unix)'.dependencies]
daemonize = "0.2"
